### PR TITLE
Polishing

### PR DESCRIPTION
**Pull request by aminya**
* Remove visualization feature from the readme
* Moving Test to extras 
* Checking nightly

### CODE REVIEW

**Comment by Datseris** [comment]
Hi, I don't agree with running tests on nightly: it is a waste of energy in a planet already suffering from massive electricity consumption. This goes for any repository.

**Comment by aminya** [comment]
@Datseris I think we need to test nightly to fix any issue, and also report Julia maintainers to fix if anything exists. 
Also, we need to check compatibility (for this repository probably not needed). For something like MusicVisualizations.jl checking compatibility is important.

**Comment by Datseris** [comment]
Compatibility of Julia packages has nothing to do with nightly. Nightly is the under-development julia branch, which 99% of the time it fails by itself, giving you confusion on why your tests fail and wasting your time reading error messages on Travis.

Also:

> to fix any issue

Which issue? Julia's issues you mean, since nightly branches are branches for the 1.x release, they are by definition non-breaking. They should never have any impact on whether our packages work or not. 

Of course the reality is not always so cool. So I believe the way to test if your packages work with latest Julia versions is to use the release candidates, which are supposed to be for people to test out the version. The nightlies are not supposed for people to test out the new versions, they are supposed for people who actually develop Julia.

My initial assessment still holds, I am not going to be running twice as many computing power on travis as I still haven't seen an argument on why this is helpful (besides developing the actual core Julia lang, which we don't do in JuliaMusic).

**Comment by Datseris** [comment]
thanks for understanding.

**Comment by aminya** [comment]
Oh, no problem. While I am skeptical for MusicVisualizations.jl nightly testing (as it does plotting) because I test the packages on nightly myself, there is no need to use CI. 
I hope this saves energy in reality.

**Pull request merged**
